#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "ACRN Multiboot Ubuntu Service VM" --id ubuntu-service-vm {
  load_video
  insmod gzio
  insmod part_gpt
  insmod ext2

  search --no-floppy --fs-uuid --set a26e612f-0fdc-4137-9f65-a10a03241c00
  echo 'loading ACRN...'
  multiboot2 /boot/acrn/acrn.bin  root=PARTUUID="9ad0c8ce-2c6e-415e-9591-984a832bb251" uart=port@0x248,5
  module2 /boot/bzImage Linux_bzImage
}
